name: golang-migrate-dev

on:
    push:
        branches: [dev]
        paths: 
            - "migrations/**"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run docker compose
        run: docker compose up -d
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false
      - name: Install golang-migrate
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - name: Run migrate on local container
        run: migrate -source file://migrations -database "postgres://postgres:password@localhost:5432/postgres?sslmode=disable" up
  migrate:
    needs: test
    name: migrate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false
      - name: Install golang-migrate
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - name: Run migrate on dev 
        run: migrate -source file://migrations -database ${{ secrets.POSTGRES_CONNECTION_STRING_DEV }} up
        